---
# from GitHub, overriding the name and specifying a specific tag
collections:
  - name: inwx.collection
  - name: community.proxmox
  - name: imp1sh.ansible_managemynetwork
  - name: community.general

