all:
  children:
    lxc:
      hosts:
        git.rackmonkey.de:
        proxy.rackmonkey.de:
        monitoring.rackmonkey.de:
    # meta hosts werden nicht direkt provisioniert oder sind gar keine Hosts.
    meta:
      hosts:
        inwx:
        pve: # irgendwie en ghost der durch das proxmox inventory dazu kommt
    proxmox_host:
      hosts:
        pve.rackmonkey.de:
  vars:
    ansible_user: root
